In [4]:
import re
import string
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

def tokenizing(data):

    data = re.sub(r'[^a-zA-Z0-9\s]','', data)
    data = re.sub(r'\d+', '', data)
    data = data.translate(str.maketrans('', '', string.punctuation))
    line = data.split(' ')
    lines = np.asarray(line)
    lines = np.char.strip(lines)
    lines = lines[lines != '']


    return lines

In [6]:
text = open('orange.txt', 'r')
corpus = tokenizing(text.read().lower())

vectorizer = TfidfVectorizer(stop_words='english')
response = vectorizer.fit_transform(corpus)
print(response)

  (0, 387)	1.0
  (1, 375)	1.0
  (3, 90)	1.0
  (5, 1387)	1.0
  (6, 495)	1.0
  (7, 708)	1.0
  (8, 1161)	1.0
  (9, 574)	1.0
  (10, 495)	1.0
  (11, 52)	1.0
  (12, 1249)	1.0
  (15, 919)	1.0
  (16, 980)	1.0
  (19, 567)	1.0
  (22, 891)	1.0
  (24, 1098)	1.0
  (27, 634)	0.6624466396106586
  (27, 1225)	0.7491091039818875
  (28, 180)	1.0
  (31, 1567)	1.0
  (35, 465)	1.0
  (39, 1027)	1.0
  (40, 1330)	1.0
  (42, 692)	1.0
  (43, 485)	1.0
  :	:
  (6799, 1504)	0.7652178948121855
  (6799, 791)	0.6437713673806928
  (6801, 883)	1.0
  (6804, 789)	1.0
  (6805, 1308)	1.0
  (6807, 1176)	1.0
  (6810, 1080)	1.0
  (6813, 344)	1.0
  (6816, 617)	1.0
  (6819, 475)	1.0
  (6822, 68)	1.0
  (6824, 1221)	1.0
  (6825, 1323)	1.0
  (6828, 121)	1.0
  (6830, 1198)	1.0
  (6831, 1367)	1.0
  (6833, 1433)	1.0
  (6836, 1523)	1.0
  (6839, 757)	1.0
  (6842, 178)	1.0
  (6850, 1218)	1.0
  (6852, 722)	1.0
  (6855, 479)	1.0
  (6858, 1308)	0.7071067811865476
  (6858, 789)	0.7071067811865476

In [8]:
vectorizer.get_feature_names_out()

array(['abjure', 'able', 'abound', ..., 'young', 'youngster', 'zero'],
      dtype=object)

In [9]:
df = pd.DataFrame(
    response.todense(),
    columns=vectorizer.get_feature_names_out()
)

df.transpose()

,0,1,2,3,4,5,6,7,8,9,...,6849,6850,6851,6852,6853,6854,6855,6856,6857,6858
abjure,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
able,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
abound,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
absence,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
absolute,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
yes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
yesterday,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
young,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
youngster,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
zero,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0