In [1]:
corpus = open('orange.txt', 'r')

print(corpus)

<_io.TextIOWrapper name='orange.txt' mode='r' encoding='cp1252'>

In [2]:
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd

vectorizer = TfidfVectorizer(stop_words='english')
response = vectorizer.fit_transform(corpus)
print(response)

  (1, 400)	0.7281363064145794
  (1, 411)	0.6854323593768635
  (2, 13)	0.30308397998114545
  (2, 3)	0.28530862375309646
  (2, 12)	0.30308397998114545
  (2, 14)	0.6061679599622909
  (2, 10)	0.6061679599622909
  (3, 731)	0.5148701198938749
  (3, 519)	0.4846738693600748
  (3, 1415)	0.4846738693600748
  (3, 114)	0.5148701198938749
  (4, 1275)	0.45239407812828164
  (4, 75)	0.45239407812828164
  (4, 597)	0.45239407812828164
  (4, 1189)	0.45239407812828164
  (4, 519)	0.4258619404194846
  (7, 1002)	0.6796907627108469
  (7, 942)	0.7334987846517178
  (9, 1251)	0.41631804973527764
  (9, 1125)	0.4647644212410564
  (9, 916)	0.5525727618210478
  (9, 590)	0.5525727618210478
  (10, 490)	0.45288336929864953
  (10, 21)	0.45288336929864953
  (10, 16)	0.45288336929864953
  :	:
  (732, 1203)	0.4618143446356029
  (732, 1334)	0.43590435540225986
  (732, 812)	0.43590435540225986
  (732, 907)	0.5011503877659387
  (732, 814)	0.3943990185250447
  (733, 640)	0.5517956546864566
  (733, 1107)	0.5517956546864566
  (733, 369)	0.40239927678590304
  (733, 500)	0.4786626504966431
  (734, 1394)	0.3963357673974527
  (734, 1039)	0.3963357673974527
  (734, 1349)	0.3963357673974527
  (734, 91)	0.3963357673974527
  (734, 145)	0.3565991795197066
  (734, 1247)	0.3730913535823604
  (734, 1224)	0.3245176497108338
  (735, 203)	0.5242022901332337
  (735, 1543)	0.5242022901332337
  (735, 1458)	0.5242022901332337
  (735, 779)	0.41908934257174724
  (736, 504)	0.568616013261397
  (736, 812)	0.4945864610362741
  (736, 1244)	0.41706158898735884
  (736, 745)	0.5080548130011844
  (737, 1334)	1.0

In [3]:
vectorizer.get_feature_names_out()

array(['000', '10', '12th', ..., 'young', 'youngster', 'zero'],
      dtype=object)

In [4]:
df = pd.DataFrame(
    response.todense(),
    columns=vectorizer.get_feature_names_out()
)

df.transpose()

,0,1,2,3,4,5,6,7,8,9,...,729,730,731,732,733,734,735,736,737,738
000,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12th,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,0.0,0.0,0.285309,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1869,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
yes,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
yesterday,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
young,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
youngster,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
zero,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0